name: Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: bru
            asset_name: bru-aarch64-apple-darwin.tar.gz
          - os: macos-13
            target: x86_64-apple-darwin
            artifact_name: bru
            asset_name: bru-x86_64-apple-darwin.tar.gz
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: bru
            asset_name: bru-x86_64-unknown-linux-gnu.tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (Linux only)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create tarball
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ${{ matrix.asset_name }} ${{ matrix.artifact_name }}
          mv ${{ matrix.asset_name }} ${{ github.workspace }}/

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate SHA256
        run: |
          shasum -a 256 ${{ matrix.asset_name }} | tee ${{ matrix.asset_name }}.sha256

      - name: Upload SHA256
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
