name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: bru-aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: bru-x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: bru-linux-x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ${{ matrix.asset_name }}.tar.gz bru
          mv ${{ matrix.asset_name }}.tar.gz ${{ github.workspace }}/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset_name }}.tar.gz
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
