name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        id: version
        run: |
          # Remove 'v' prefix from tag name
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Trigger tap repository update
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TAP_UPDATE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/nijaru/homebrew-tap/dispatches \
            -d '{"event_type":"release-published","client_payload":{"version":"${{ steps.version.outputs.version }}"}}'

      - name: Workflow result
        run: |
          echo "✓ Triggered homebrew-tap update for v${{ steps.version.outputs.version }}"
          echo "Formula will be updated automatically in nijaru/homebrew-tap"
